global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: tatou-server
    metrics_path: /metrics
    static_configs:
      - targets: ['server:5000']
    relabel_configs:
      - source_labels: ['__address__']
        target_label: instance
        replacement: tatou-server
    scheme: http
    http_headers:
      X-Metrics-Token:
        values: ['ultra-mega-giga-secret-token-for-metrics-access-which-is-not-hardcoded-anywhere']
